#!/bin/bash
DOCKER_HOST_IP=`/sbin/ifconfig docker0 | grep "inet addr:" | awk -F"inet addr:| Bcast" '{print $2}'`
docker run --rm=true -it -v /tmp/.X11-unix:/tmp/.X11-unix -e PULSE_SERVER=${DOCKER_HOST_IP} -e DISPLAY=unix$DISPLAY --name pavucontrol pavucontrol
