#!/bin/bash
export DISPLAY=:0 
xhost local:root
mkdir -p ~/.mozilla
docker run --rm=true -u="firefox" -v ${HOME}:${HOME} -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v $HOME/Downloads:/home/firefox/Downloads -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v $HOME/.mozilla:/home/firefox/.mozilla:rw -v /dev/snd:/dev/snd --privileged firefox "$@"
