#!/bin/bash

set -e

SRC=${1:-$(pwd)}
OUT_DIR=${2:-$(pwd)}

if [ $# -lt 1 ]; then
    echo "Usage: $0 input_file_or_dir [output_dir]"
    exit 1
fi

export DISPLAY=:0 
xhost local:root > /dev/null

if [ -f $SRC ]; then
    FILENAME=$(basename $SRC)
    V_IN="$(realpath $SRC):/plantuml/in/$FILENAME"
elif [ -d $SRC ]; then
    V_IN="$(realpath $SRC):/plantuml/in"
else 
    echo "Must specify an input_file_or_dir that exists."
    exit 1
fi

V_OUT="$(realpath ${OUT_DIR}):/plantuml/out"

docker run --rm=true -t -i -u $(id -u ${USER}) -v $V_IN  -v $V_OUT -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY plantuml

