#!/bin/bash
export DISPLAY=:0 
xhost local:root
mkdir -p ~/.Skype
docker rm -f skype 2>/dev/null || true
docker run --rm=true \
    -u="skype" \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/timezone:/etc/timezone:ro \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=unix$DISPLAY \
    -v /dev/snd:/dev/snd \
    -v /dev/video0:/dev/video0 \
    -e PULSE_SERVER=$(/sbin/ifconfig docker0 | grep "inet " | awk '{print $2}') \
    -v $HOME/Downloads:/home/skype/Downloads \
    -v $HOME/.Skype:/home/skype/.Skype:rw \
    --privileged \
    --name skype \
    skype
docker rm -f skype 2>/dev/null || true
